############# config ##################
#
set base_path    /var/spool/apt-mirror
#
set mirror_path  $base_path/mirror
set skel_path    $base_path/skel
set var_path     $base_path/var
# set cleanscript $var_path/clean.sh
set defaultarch  amd64
# set postmirror_script $var_path/postmirror.sh
# set run_postmirror 0
set nthreads     8
set _tilde 0
#
############# end config ##############

deb http://lliurex.net/noble noble main restricted universe multiverse
deb http://lliurex.net/noble noble-security main restricted universe multiverse
deb http://lliurex.net/noble noble-updates main restricted universe multiverse
#deb http://lliurex.net/noble noble-proposed main restricted universe multiverse
deb http://lliurex.net/noble noble-backports main restricted universe multiverse

#deb-src http://lliurex.net/noble noble main restricted universe multiverse
#deb-src http://lliurex.net/noble noble-security main restricted universe multiverse
#deb-src http://lliurex.net/noble noble-updates main restricted universe multiverse
#deb-src http://lliurex.net/noble noble-proposed main restricted universe multiverse
#deb-src http://lliurex.net/noble noble-backports main restricted universe multiverse

clean http://lliurex.net/noble
