#!/bin/bash

# This script is licensed under GPLv3 or higher
# Authors:
#    - Angel Berlanas Vicente <aberlanas@fsfe.org>
#    - M.Angel Crujera <me@crujera.net>

echo " * [ Senia - Internet, ¡Sal de este equipo! ] "
echo ""

if [ $(id -u) -ne 0 ]; then
        echo " * ERROR : Este software ha de ejecutarse usando sudo"
        echo ""
        echo " sudo $(basename $0) "
        exit 1
fi


echo " - Para proteger que el alumnado no pueda poner " 
echo "   Internet, aseguraremos la accion con una contrasenya"
echo "   que solicitaremos para activar Internet de nuevo"
echo ""
sleep 0.5
echo -n " -> Introduce la contrasenya: "
read -s PASSWIFI
echo ""
echo "$PASSWIFI" | sha256sum  > /tmp/senia-internet-lock.gpg

echo " * Desactivo internet ... " 
sleep 0.5
echo " * Para activarlo luego : senia-internet-ven-a-mi"

iptables -F 
iptables -A OUTPUT -j DROP







exit 0
